name: deploy-components-to-stage
on:
  push:
    branches:
      - main
    paths: 
      - 'package.json'
    
jobs:
  react_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org/'

      -  name: check out
         uses: actions/checkout@v3
         with:
           fetch-depth: 0 
      -  name: Check for version change
         id: version_changed
         uses: EndBug/version-check@v2
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           diff-search: true # Search for changes in the last commit

      - name: hello-world
        run: echo "Hello World"
        
      - name: discord
        uses: sebastianpopp/discord-action@releases/v2
        with:
          webhook: ${{ secrets.TASKMASTER_ALLMANT }}
          message: ${{ github.actor }} has successfully pushed to main

      - name: Install dependencies
        run: npm install

      - name: Build component (if needed)
        run: npm run build

      - name: Publish to NPM
        if: steps.version_changed.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
